#!/bin/bash
#
# test bad file name
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_monty

# run command
touch $tmp_file
chmod a-r $tmp_file
$MONTY $tmp_file > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "Error: Can't open file $tmp_file"`
if [ $nmatch -eq 1 ]; then
      print_ok
else
	print_ko
fi

# clean up
stop_monty
rm -r $tmp_file
